### ISSUE TITLE
Harvester Crashes

### ISSUE THREAD

**Issue by mda1125** [highmeh/lure#1]
Love the script idea and indeed when all is working it does upload to the GoPish server!

Fixed the Hunter.io which which had a limit of 1000 but now a person account has a limit of 10

But the Harvester throws so funky errors even though I changed the location in the config.py to the correct location.

[+] Checking hunter.io (99/100 queries remaining)
[+] Checking theHarvester...
    (Note: This may take a while)
Traceback (most recent call last):
  File "./lure.py", line 305, in <module>
    start_discovery(company_domain,print_result,exclusion_list,enable_hibp)
  File "./lure.py", line 85, in start_discovery
    company_domain,config.HARVESTER_LOCATION)
  File "/Users/user/workspace/lure/resources/harvester.py", line 20, in get_harvester_emails
    subprocess.check_call(subprocess_cmd, stdout=DEVNULL, stderr=DEVNULL)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/Users/user/workspace/lure/resources/theHarvester.py', '-d', 'microsoft.com', '-b', 'bing,dogpile,google,yahoo', '-f', '/tmp/harvester_microsoft_results.xml', '>/dev/null', '2>&1']' returned non-zero exit status 2.

**Comment by Mike-Misiaczek** [comment]
I'm having the same issue.

**Comment by Mike-Misiaczek** [comment]
Any luck with this?
